@startuml

title __BEAN's Class Diagram__\n

  namespace com.example.netnew {
    namespace bean {
      class com.example.netnew.bean.NewsDataBean {
          - category : String
          - content : String
          - pic : String
          - src : String
          - time : String
          - title : String
          - url : String
          - weburl : String
          + getCategory()
          + getContent()
          + getPic()
          + getSrc()
          + getTime()
          + getTitle()
          + getUrl()
          + getWeburl()
          + setCategory()
          + setContent()
          + setPic()
          + setSrc()
          + setTime()
          + setTitle()
          + setUrl()
          + setWeburl()
      }
    }
  }
  

  namespace com.example.netnew {
    namespace bean {
      class com.example.netnew.bean.NewsTitle {
          - charge : boolean
          - code : String
          - msg : String
          + getCharge()
          + getCode()
          + getMsg()
          + getResult()
          + setCharge()
          + setCode()
          + setMsg()
          + setResult()
      }
    }
  }
  

  namespace com.example.netnew {
    namespace bean {
      class com.example.netnew.bean.NewsTitle.Result {
          - msg : String
          - result : List<String>
          - status : String
          + getMsg()
          + getResult()
          + getStatus()
          + setMsg()
          + setResult()
          + setStatus()
      }
    }
  }
  

  namespace com.example.netnew {
    namespace bean {
      class com.example.netnew.bean.User {
          - account : String
          - address : String
          - id : Integer
          - name : String
          - password : String
          - phone : String
          - photo : String
          - sex : String
          + User()
          + getAccount()
          + getAddress()
          + getId()
          + getName()
          + getPassword()
          + getPhone()
          + getPhoto()
          + getSex()
          + setAccount()
          + setAddress()
          + setId()
          + setName()
          + setPassword()
          + setPhone()
          + setPhoto()
          + setSex()
      }
    }
  }
  

  com.example.netnew.bean.NewsTitle o-- com.example.netnew.bean.NewsTitle.Result : result
  com.example.netnew.bean.NewsTitle +-down- com.example.netnew.bean.NewsTitle.Result
  com.example.netnew.bean.User .up.|> java.io.Serializable


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
